on: [push]
name: doc
jobs:
  doc:
    runs-on: ubuntu-latest
    env:
      RUSTC_BOOTSTRAP: 1
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
      - run: sudo apt-get install -y libfuse-dev
      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --features std --package rcore-fs-dfs --no-deps
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
